device: /dev/ttyACM0
mqtt:
  host: localhost
  port: 8883
  cafile: /home/karel/clown/tls/ca.crt
  certfile: /home/karel/clown/tls/client.crt
  keyfile: /home/karel/clown/tls/client.key
rename:
  836d1983631e: room
